// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa-c0kkUpHIes9nvjc-QHisDaFKkaVezA',
    appId: '1:860343701349:web:f9f57012f065ba3ef4db8c',
    messagingSenderId: '860343701349',
    projectId: 'authorization-c9f82',
    authDomain: 'authorization-c9f82.firebaseapp.com',
    storageBucket: 'authorization-c9f82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB423UvhwNTVdxtFNzWlltX8tKwIlcEHHE',
    appId: '1:860343701349:android:9f5e3565ef746874f4db8c',
    messagingSenderId: '860343701349',
    projectId: 'authorization-c9f82',
    storageBucket: 'authorization-c9f82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtRcjDUAIk9PA3lpMrQV0rDxFhBUlMiG8',
    appId: '1:860343701349:ios:4ef10e3696e821d7f4db8c',
    messagingSenderId: '860343701349',
    projectId: 'authorization-c9f82',
    storageBucket: 'authorization-c9f82.appspot.com',
    iosBundleId: 'com.company.authorization',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtRcjDUAIk9PA3lpMrQV0rDxFhBUlMiG8',
    appId: '1:860343701349:ios:c89ffb900b527de4f4db8c',
    messagingSenderId: '860343701349',
    projectId: 'authorization-c9f82',
    storageBucket: 'authorization-c9f82.appspot.com',
    iosBundleId: 'com.company.authorization.RunnerTests',
  );
}
